_format_version: "3.0"

services:
  - name: auth-service
    url: http://auth-service:8002
    routes:
      # PUBLIC - register (no JWT)
      - name: register-route
        paths:
          - /auth/register
        strip_path: false

      # PUBLIC - login (no JWT)
      - name: login-route
        paths:
          - /auth/jwt/login
        strip_path: false

      # PROTECTED - logout (JWT required)
      - name: logout-route
        paths:
          - /auth/jwt/logout
        strip_path: false
        plugins:
          - name: jwt
            config:
              claims_to_verify: ["exp"]
              key_claim_name: "iss"
              secret_is_base64: false
              run_on_preflight: false

      # PROTECTED - user info (JWT required)
      - name: users-me-route
        paths:
          - /users/me
        strip_path: false
        plugins:
          - name: jwt
            config:
              claims_to_verify: ["exp"]
              key_claim_name: "iss"
              secret_is_base64: false
              run_on_preflight: false

  - name: order-service
    url: http://order-service:8003
    routes:
      - name: scan-qr-route
        paths:
          - /order-service/scan_qr
        strip_path: false

      - name: order-route
        paths:
          - /order-service/order
        strip_path: false


consumers:
  - username: "auth-consumer"
    custom_id: "auth-service"
    jwt_secrets:
      - algorithm: HS256
        key: "auth-service"
        secret: "xbfwxdmvq(=bi-kwt@8+2lzr9zu_iin%h_iviq6h@hguypn%hg"
