services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:${DB_PORT}"
    env_file:
      - .env

  api-gateway:
    image: api-gateway:latest
    container_name: api-gateway
    build:
      context: ../api-gateway
      dockerfile: Dockerfile
    command: >
      uvicorn api.main:app --host 0.0.0.0 --port ${API_GATEWAY_PORT}
    volumes:
      - ../api-gateway:/app
    ports:
      - "${API_GATEWAY_PORT}:${API_GATEWAY_PORT}"
    env_file:
      - .env
    depends_on:
      - postgres

  auth-service:
    image: auth-service:latest
    container_name: auth-service
    build:
      context: ../auth-service
      dockerfile: Dockerfile
    command: >
      uvicorn api.main:app --host 0.0.0.0 --port ${AUTH_SERVICE_PORT}
    volumes:
      - ../auth-service:/app
    ports:
      - "${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}"
    env_file:
      - .env
    depends_on:
      - postgres

  order-service:
    image: order-service:latest
    container_name: order-service
    build:
      context: ../order-service
      dockerfile: Dockerfile
    command: >
      uvicorn api.main:app --host 0.0.0.0 --port ${ORDER_SERVICE_PORT}
    volumes:
      - ../order-service:/app
    ports:
      - "${ORDER_SERVICE_PORT}:${ORDER_SERVICE_PORT}"
    env_file:
      - .env
    depends_on:
      - postgres

  payment-service:
    image: payment-service:latest
    container_name: payment-service
    build:
      context: ../payment-service
      dockerfile: Dockerfile
    command: >
      uvicorn api.main:app --host 0.0.0.0 --port ${PAYMENT_SERVICE_PORT}
    volumes:
      - ../payment-service:/app
    ports:
      - "${PAYMENT_SERVICE_PORT}:${PAYMENT_SERVICE_PORT}"
    env_file:
      - .env
    depends_on:
      - postgres

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # Port do komunikacji aplikacyjnej (AMQP)
      - "15672:15672"   # Port do UI (RabbitMQ Management)
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_LOAD_DEFINITIONS: /etc/rabbitmq/definitions.json
    volumes:
      - ./rabbitmq_definitions.json:/etc/rabbitmq/definitions.json

volumes:
  postgres_data: